name: RETIRE

on:
  release:
    types:
        - deleted

jobs:
  retire:
    runs-on: ubuntu-latest
    env:
      REASON: "deprecated"
      VERSION: ${{ github.event.release.tag_name }}
      MESSAGE: "Version removed from source code repository"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Elixir
        uses: erlef/setup-beam@v1.24.0
        with:
          otp-version: '26'
          elixir-version: '1.18'
      - name: Authenticate
        run: mix hex.config api_key "$HEX_AUTH_KEY"
        env:
          HEX_AUTH_KEY: ${{ secrets.HEX_AUTH_KEY }}
      - name: Check user
        run: mix hex.user whoami
      - name: Retire version
        run: |
          echo "Attempting to retire version $VERSION" 
          mix hex.retire ex_launch_dark "$VERSION" "$REASON" --message "$MESSAGE"
